# Changes here will be overwritten by Copier
_commit: 3d9a86d
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: timkpaine
project_description: Alias for csp-adapter-discord
project_name: csp-discord
python_version_primary: '3.11'
team: the csp-discord authors
